@startuml
left to right direction
skinparam packageStyle rectangle

actor "Agent" as Agent
actor "Admin" as Admin

Admin -up-|> Agent

rectangle "Admin Workspace" {

    usecase "Login / Authentication" as Login
    usecase "View Analytics & Reports" as Analytics
    usecase "Manage Users & Roles" as ManageUsers
}

Analytics ..> Login : <<include>>
ManageUsers ..> Login : <<include>>

Admin -- Analytics
Admin -- ManageUsers

@enduml